### ISSUE TITLE
Error starting docker image of development branch

### ISSUE THREAD

**Issue by KlausPopp** [thiagoralves/OpenPLC_v3#168]
I've build a docker image from the development branch
```
docker build -t openplc:v3 .
```
Resulting in the following error
```
docker run -it --rm --cap-add=SYS_NICE --cap-add=IPC_LOCK -p 8080:8080 openplc:v3

Traceback (most recent call last):
  File "/workdir/webserver/webserver.py", line 34, in <module>
    import flask
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 25, in <module>
    from . import cli, json
  File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 21, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.9/dist-packages/itsdangerous/__init__.py)
``` 
Changing requirements.txt fixed the problem
```
markupsafe==2.0.1
Flask==1.1.4
Flask-Login==0.4.1
pyserial==3.4
pymodbus==2.2.0
```

**Comment by mhanuel26** [comment]
your fix also solve mine, I was getting the following

```
docker run -it --rm --privileged -p 8080:8080 openplc:v3
Traceback (most recent call last):
  File "/workdir/webserver/webserver.py", line 34, in <module>
    import flask 
  File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
```
